[build]
  edge_functions = "netlify/edge-functions"

[dev]
    edge_functions = "netlify/edge-functions"
    framework = "vite"
    command = "npm run dev"
    targetPort = 8080

[[edge_functions]]
  path = "/admin"
  function = "auth"